name: Successful Tests CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Run Successful Tests Only
      run: mvn clean test -Dtest=CalculatorTest,LoginTest#testLoginSuccess

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: success-testng-report
        path: target/surefire-reports/
